FROM python:3.9-slim
# ...
RUN pip install streamlit pandas pyspark
# ...
WORKDIR /app

RUN pip install streamlit pandas
RUN pip install streamlit pandas numpy scikit-learn
COPY app_ui.py .

# Streamlit ใช้ Port 8501 เป็นหลัก
EXPOSE 8501

CMD ["streamlit", "run", "app_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]